### PR TITLE
updated instructions UI

### PR DESCRIPTION
**Pull request by jdexcond**
**summary**
- updated instructions page to match Figma designs
- idk how to make it so it wraps to the size of a mobile screen idk why i couldn't figure that out so if anyone knows pls lmk
image

### CODE REVIEW

**Review by e33lin — COMMENTED** [review]
oops i totally meant to make a doc on this, but heres how to resize your tab to view it in different screen sizes: https://www.notion.so/jennahirji/checking-out-the-app-in-mobile-view-c1f00eb5e56143fb80a6c2edda7c847a?pvs=4

otherwise i think the only off thing is that the build a list button isnt centered i tried sticking a "margin: auto;" into the div class but its not working for me LOL

**Comment by jdexcond** [comment]
omg thank u!! ok let me fix that

**Comment by jdexcond** [comment]
@e33lin fixed it!! lmk if there's anything else that looks off

**Comment by e33lin** [comment]
> @e33lin fixed it!! lmk if there's anything else that looks off

looks good thank u JD this is gorgeous

**Review by e33lin — APPROVED** [review]

**Pull request merged**
